// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 40: // ['(','(']
			return 2
		case r == 41: // [')',')']
			return 3
		case r == 43: // ['+','+']
			return 4
		case r == 44: // [',',',']
			return 5
		case r == 48: // ['0','0']
			return 6
		case 49 <= r && r <= 57: // ['1','9']
			return 7
		case r == 59: // [';',';']
			return 8
		case r == 61: // ['=','=']
			return 9
		case 97 <= r && r <= 101: // ['a','e']
			return 10
		case r == 102: // ['f','f']
			return 11
		case 103 <= r && r <= 107: // ['g','k']
			return 10
		case r == 108: // ['l','l']
			return 12
		case 109 <= r && r <= 122: // ['m','z']
			return 10
		case r == 123: // ['{','{']
			return 13
		case r == 125: // ['}','}']
			return 14
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S3
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S7
	func(r rune) int {
		switch {
		case 48 <= r && r <= 57: // ['0','9']
			return 7
		}
		return NoState
	},
	// S8
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 62: // ['>','>']
			return 15
		}
		return NoState
	},
	// S10
	func(r rune) int {
		switch {
		case 97 <= r && r <= 122: // ['a','z']
			return 10
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case 97 <= r && r <= 109: // ['a','m']
			return 10
		case r == 110: // ['n','n']
			return 16
		case 111 <= r && r <= 122: // ['o','z']
			return 10
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		case 97 <= r && r <= 100: // ['a','d']
			return 10
		case r == 101: // ['e','e']
			return 17
		case 102 <= r && r <= 122: // ['f','z']
			return 10
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		case 97 <= r && r <= 122: // ['a','z']
			return 10
		}
		return NoState
	},
	// S17
	func(r rune) int {
		switch {
		case 97 <= r && r <= 115: // ['a','s']
			return 10
		case r == 116: // ['t','t']
			return 18
		case 117 <= r && r <= 122: // ['u','z']
			return 10
		}
		return NoState
	},
	// S18
	func(r rune) int {
		switch {
		case 97 <= r && r <= 122: // ['a','z']
			return 10
		}
		return NoState
	},
}
